### ISSUE TITLE
buildPreprocessed function needs another function to work - MakeFilter

### ISSUE THREAD

**Issue by biiyukari** [lfbortoletto/social-stressor#5]
When I run the code it appears:
Unrecognized function or variable 'MakeFilter'.

Error in hmrBandpassFiltLOB (line 38)
    [fb,fa] = MakeFilter(FilterType,FilterOrder,fs,lpf,'low');

Error in buildPreprocessed>PreProcessFinometer (line 111)
filtHR = hmrBandpassFiltLOB(yqHR, physiology.PreProcParams.fSample, bpf.HR(1), bpf.HR(2));

Error in buildPreprocessed>PreprocessPhysiology (line 74)
    [physiology] = PreProcessFinometer(physiology, finometer, nirs);

Error in buildPreprocessed (line 17)
    PreprocessPhysiology(rawPath, preprocPath, dataName);

**Comment by lfbortoletto** [comment]
I opened a new pull request (PR) to fix this issue. Please, check the updates and allow merge afterwards. 

Let me know if the error persists. Otherwise, you can close this issue.
